# Use this config for evaluating the a trained model.
# Usage: python tools/train_net.py --num-gpus 4 --config-file ./configs/PascalVOC-Detection/iOD/eval.yaml --eval-only
# Do change:
#   -- WEIGHTS
#   -- NUM_BASE_CLASSES
#   -- NUM_NOVEL_CLASSES


_BASE_: "../../Base-RCNN-C4.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "./output/10_p_10_ft/model_final.pth"
  WEIGHTS: "./output/plus_10/10_p_10_ft_with_extras/model_final.pth"
#  WEIGHTS: "/home/joseph/workspace/detectron2/output/15_p_5/model_0019999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    # Maximum number of foreground classes to expect
    NUM_CLASSES: 20
    # Flag to turn on/off Incremental Learning
    LEARN_INCREMENTALLY: False
    # Flag to select whether to learn base classes or iOD expanded classes
    TRAIN_ON_BASE_CLASSES: False
    # Number of base classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to True
    NUM_BASE_CLASSES: 10
    # Number of novel classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to False
    NUM_NOVEL_CLASSES: 10
    POSITIVE_FRACTION: 0.25
    NMS_THRESH_TEST: 0.4
  RPN:
    FREEZE_WEIGHTS: False
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval',)
  TEST: ('voc_2007_test',)
OUTPUT_DIR: ./output/eval
SEED: 9999
VERSION: 2